In [1]:
import numpy as np
from openbabel import openbabel as ob
from openbabel import pybel

In [2]:
molecules = pybel.readfile("sdf", "benzene.sdf")
for mol in molecules:

    n = len(mol.atoms)

    # Pre-allocate memory for  the adjacency matrix
    A = np.zeros((n, n), dtype=int)

    # Loop over molecular bonds
    for bond in ob.OBMolBondIter(mol.OBMol):
        # Bonds are 1-indexed
        i: int = bond.GetBeginAtomIdx() - 1
        j: int = bond.GetEndAtomIdx() - 1

        # A molecular graph is undirected
        A[i, j] = A[j, i] = bond.GetBondOrder()
    print(A)

[[0 1 0 0 0 2 1 0 0 0 0 0]
 [1 0 2 0 0 0 0 1 0 0 0 0]
 [0 2 0 1 0 0 0 0 1 0 0 0]
 [0 0 1 0 2 0 0 0 0 1 0 0]
 [0 0 0 2 0 1 0 0 0 0 1 0]
 [2 0 0 0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]]
